package com.example.data.update

import android.content.Context
import android.content.pm.PackageInfo
import android.content.pm.PackageManager
import android.os.Build
import com.example.BuildConfig
import com.squareup.moshi.Moshi
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.OkHttpClient
import okhttp3.Request
import java.io.File
import java.io.IOException
import java.util.concurrent.TimeUnit

/**
 * Fetches the published update manifest, downloads a release, and vets the file
 * it produced.
 *
 * ## Why this exists as a self-contained piece of app code
 *
 * There is no updater library here, deliberately. The only job is: fetch a
 * small JSON file, compare one integer against `BuildConfig.VERSION_CODE`, and
 * stream a ~2.5 MB APK into the cache directory. A library would add a
 * dependency and a Play Services requirement for that, and the app is
 * deliberately not on the Play Store - which is also why the install handoff
 * uses `ACTION_VIEW` on a `FileProvider` URI rather than Play Core's in-app
 * update flow.
 *
 * ## What this cannot do
 *
 * It cannot install silently. Since Android 8 every install is user-confirmed,
 * and from Android 8 the app must hold `REQUEST_INSTALL_PACKAGES` *and* have
 * that permission granted per-app in Settings before the installer will even
 * open.
 *
 * ## What this no longer does
 *
 * The permission check, the Settings hand-off and the installer intents used to
 * live here too. They moved to `UpdateInstallation` in the presentation layer,
 * because they are all about *this device's* UI and none of them are about
 * fetching or verifying a release - and because the order they have to be
 * called in is the actual logic of the install flow, which is easier to read
 * when the order is the file's shape. What stays here is everything that is
 * true regardless of which device is asking.
 */
class UpdateManager(private val context: Context) {

    private val moshi = Moshi.Builder().build()

    // Its own client, deliberately not the shared one: that client carries the
    // AniList auth interceptor, and the update manifest is a public file that
    // must never be requested with a user's AniList bearer token attached.
    private val client: OkHttpClient = OkHttpClient.Builder()
        .connectTimeout(15, TimeUnit.SECONDS)
        .readTimeout(30, TimeUnit.SECONDS)
        .build()

    /**
     * Asks GitHub whether something newer exists.
     *
     * Never throws. A failed check is a normal outcome - the user is offline,
     * or GitHub is down - and it must not be able to take down whatever screen
     * asked, so every failure path is folded into [UpdateCheckResult.Failed]
     * with a message that can be shown verbatim.
     */
    suspend fun checkForUpdate(): UpdateCheckResult = withContext(Dispatchers.IO) {
        val installedVersion = BuildConfig.VERSION_NAME

        val body = try {
            val request = Request.Builder()
                .url(UPDATE_MANIFEST_URL)
                // Force a revalidation. OkHttp's cache is per-client and this
                // client has no cache configured, but being explicit costs
                // nothing and survives someone adding one later.
                .header("Cache-Control", "no-cache")
                .build()

            client.newCall(request).execute().use { response ->
                if (!response.isSuccessful) {
                    return@withContext UpdateCheckResult.Failed(
                        "GitHub answered ${response.code}."
                    )
                }
                response.body?.string()
            }
        } catch (e: IOException) {
            return@withContext UpdateCheckResult.Failed(
                "Could not reach GitHub. Check your connection and try again."
            )
        } ?: return@withContext UpdateCheckResult.Failed("GitHub sent an empty response.")

        val manifest = try {
            moshi.adapter(UpdateManifest::class.java).fromJson(body)
        } catch (e: kotlinx.coroutines.CancellationException) {
            throw e
        } catch (e: Exception) {
            // Malformed JSON, or a field of the wrong type. Worth saying so:
            // this file is generated by a workflow, so a parse failure is a
            // real signal that the manifest shape changed.
            return@withContext UpdateCheckResult.Failed(
                "The update manifest could not be read."
            )
        } ?: return@withContext UpdateCheckResult.Failed("The update manifest was empty.")

        if (!manifest.isUsable) {
            return@withContext UpdateCheckResult.Failed(
                "The update manifest is missing a download link."
            )
        }

        if (manifest.isNewerThan(BuildConfig.VERSION_CODE.toLong())) {
            UpdateCheckResult.Available(manifest)
        } else {
            UpdateCheckResult.UpToDate(installedVersion)
        }
    }

    /**
     * Streams the APK into the cache directory.
     *
     * Writes to a `.part` file and renames on completion, so a download
     * interrupted by a phone call or a process death cannot leave a truncated
     * APK behind that a later run would happily hand to the package installer -
     * which fails with an opaque `INSTALL_PARSE_FAILED_NO_CERTIFICATES` or, worse,
     * appears to succeed.
     */
    suspend fun download(
        manifest: UpdateManifest,
        onProgress: (bytesRead: Long, totalBytes: Long) -> Unit = { _, _ -> }
    ): UpdateDownloadResult = withContext(Dispatchers.IO) {
        val url = manifest.downloadUrl.orEmpty()
        if (url.isBlank()) {
            return@withContext UpdateDownloadResult.Failed("That release has no download.")
        }

        try {
            val request = Request.Builder().url(url).build()

            client.newCall(request).execute().use { response ->
                if (!response.isSuccessful) {
                    return@withContext UpdateDownloadResult.Failed(
                        "The download failed (${response.code})."
                    )
                }

                val body = response.body ?: return@withContext UpdateDownloadResult.Failed(
                    "The download came back empty."
                )

                // Bounded: the manifest declares a size and it matched in every
                // release so far. A wildly larger body means the URL is not
                // serving an APK, and writing it to disk would fill the user's
                // storage on a download they never asked for.
                val declaredSize = manifest.sizeBytes ?: 0L
                if (declaredSize > 0 && body.contentLength() > declaredSize * 2) {
                    return@withContext UpdateDownloadResult.Failed(
                        "The download was much larger than expected. Skipped."
                    )
                }

                val sizeLimit = if (declaredSize > 0) declaredSize * 2 else Long.MAX_VALUE

                var partial: File? = null
                try {
                    val directory = downloadDirectory()
                    val target = targetFileFor(directory, manifest)
                    val partFile = File(directory, "${target.name}.part")
                    partial = partFile

                    body.byteStream().use { input ->
                        partFile.outputStream().use { output ->
                            val buffer = ByteArray(DEFAULT_BUFFER_SIZE)
                            val total = body.contentLength().takeIf { it > 0 } ?: declaredSize
                            var read: Long = 0

                            // The pre-check above is a fast reject, but it compares against
                            // `contentLength()`, which is -1 for chunked transfer
                            // and then never fails. The bound is enforced here
                            // too, on bytes actually read, so a body without a
                            // Content-Length header cannot grow without limit.
                            while (true) {
                                val count = input.read(buffer)
                                if (count == -1) break
                                read += count
                                if (read > sizeLimit) {
                                    partFile.delete()
                                    return@withContext UpdateDownloadResult.Failed(
                                        "The download was much larger than expected. Skipped."
                                    )
                                }
                                output.write(buffer, 0, count)
                                onProgress(read, total)
                            }

                            output.flush()
                        }
                    }

                    // A 200 response is not proof the body is an APK. A redirect
                    // that lands on an HTML error page, or a rate-limit notice,
                    // is still a successful HTTP response, and the size guard
                    // above only catches bodies that are too *large* - so that
                    // page would be written out as anisequel-<version>.apk and
                    // handed to the package installer, which fails with an
                    // opaque parse error and nothing on screen to explain it.
                    // Every APK is a zip and every zip opens with a local file
                    // header, so four bytes are enough to tell them apart.
                    val looksLikeApk = partFile.inputStream().use { stream ->
                        val magic = ByteArray(4)
                        stream.read(magic) == 4 &&
                            magic[0] == 0x50.toByte() &&
                            magic[1] == 0x4B.toByte() &&
                            magic[2] == 0x03.toByte() &&
                            magic[3] == 0x04.toByte()
                    }

                    if (!looksLikeApk) {
                        partFile.delete()
                        return@withContext UpdateDownloadResult.Failed(
                            "That download was not an APK, so nothing was installed."
                        )
                    }

                    // Being a zip is not the same as being *our* app. Until this
                    // existed, whatever the URL served was handed straight to the
                    // package installer: a release asset replaced at the CDN, a
                    // hijacked mirror, or a future mistake in the manifest's
                    // download_url would all install, and the failure mode is a
                    // successful install of someone else's code.
                    //
                    // Android will not let a different key update an existing
                    // app, so this mostly protects against a first install from
                    // a tampered manifest rather than a silent upgrade - but it
                    // also catches a mismatched build *before* the user reaches a
                    // system dialog that says only "App not installed".
                    if (!isSignedByThisApp(partFile)) {
                        partFile.delete()
                        return@withContext UpdateDownloadResult.Failed(
                            "That APK is not signed with AniSequel's key, so it was not " +
                                "installed. The release may have been tampered with."
                        )
                    }

                    if (!partFile.renameTo(target)) {
                        partFile.delete()
                        return@withContext UpdateDownloadResult.Failed(
                            "Could not save the download."
                        )
                    }

                    UpdateDownloadResult.Success(target, manifest)
                } catch (e: Exception) {
                    partial?.delete()
                    throw e
                }
            }
        } catch (e: kotlinx.coroutines.CancellationException) {
            throw e
        } catch (e: Exception) {
            UpdateDownloadResult.Failed(
                e.message?.takeIf { it.isNotBlank() } ?: "The download failed. Check your connection."
            )
        }
    }

    /**
     * The already-downloaded APK for [manifest], if there is a usable one.
     *
     * ## Why this exists
     *
     * The install flow has a mandatory Settings round trip the first time: from
     * Android 8 the app has to be granted `REQUEST_INSTALL_PACKAGES` before it
     * may open the installer at all. The download happens before that check,
     * deliberately - the user has already asked to update, and refusing to start
     * over a setting they may have granted since last launch is worse than
     * downloading and then asking.
     *
     * Which means a user who has *not* yet granted it used to pay for the
     * download, go to Settings, grant it, come back, and then have to press
     * install again - and pressing "download" at any point started the download
     * over from zero, because every run wiped the cache directory first. That is
     * the one flow in the app where the user waits on the network twice for the
     * same bytes.
     *
     * The file name is derived from the manifest's version, so this returns the
     * right APK or nothing at all. A zero-length file, or one that somehow lost
     * its zip header, is rejected here rather than at the installer.
     */
    fun downloadedApkFor(manifest: UpdateManifest): File? {
        val file = targetFileFor(downloadDirectory(), manifest)
        if (!file.isFile || file.length() <= 0L) return null

        val looksLikeApk = runCatching {
            file.inputStream().use { stream ->
                val magic = ByteArray(4)
                stream.read(magic) == 4 &&
                    magic[0] == 0x50.toByte() &&
                    magic[1] == 0x4B.toByte() &&
                    magic[2] == 0x03.toByte() &&
                    magic[3] == 0x04.toByte()
            }
        }.getOrDefault(false)

        return file.takeIf { looksLikeApk }
    }

    /**
     * Where the APK for a release is written.
     *
     * Named after the version *code*, not the version name. The updater compares
     * codes because "1.0.9" sorts above "1.0.10", so a cache keyed on the name
     * could serve one release's APK to another when the code advanced without a
     * name change - and the name string reaches the filesystem unvalidated. The
     * code is the GitHub run number: monotonic by construction and safe in a path.
     */
    private fun targetFileFor(directory: File, manifest: UpdateManifest): File =
        File(directory, "anisequel-${manifest.versionCode ?: "unversioned"}.apk")

    private fun downloadDirectory(): File =
        File(context.cacheDir, DOWNLOAD_DIR).apply { mkdirs() }

    /**
     * Whether [apk] is signed by AniSequel's official key or matches the running app's key.
     *
     * Validates against:
     * 1. AniSequel's pinned official release signing certificate SHA-256
     * 2. The currently installed app's signing certificates or rotation history
     *
     * A debug build additionally accepts anything, so a locally signed APK can
     * be exercised end to end. A release build accepts nothing it could not
     * positively identify.
     */
    private fun isSignedByThisApp(apk: File): Boolean {
        val packageManager = context.packageManager

        // `GET_SIGNING_CERTIFICATES` alone, with no `GET_SIGNATURES` fallback.
        // The old code OR'd in the deprecated `GET_SIGNATURES` behind an
        // `SDK_INT >= P` fork, and P (28) is below the `minSdk = 31` floor, so
        // that flag described devices this build cannot be installed on.
        //
        // The deprecated `int` overload below is still correct to call on API
        // 31/32: it was only deprecated in 33, and it maps these flags onto
        // `signingInfo` on 28+. It is the `PackageInfoFlags` branch above that
        // is still needed - 33 is *above* this floor.
        val flags = PackageManager.GET_SIGNING_CERTIFICATES

        val archiveInfo = try {
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
                packageManager.getPackageArchiveInfo(
                    apk.absolutePath,
                    PackageManager.PackageInfoFlags.of(flags.toLong())
                )
            } else {
                packageManager.getPackageArchiveInfo(apk.absolutePath, flags)
            }
        } catch (e: Exception) {
            null
        }

        // Validate package name if readable
        if (archiveInfo?.packageName != null && archiveInfo.packageName != context.packageName) {
            return false
        }

        val theirs = archiveInfo?.let { signerCertificates(it) }

        // 1. Check against AniSequel's pinned official release key
        if (!theirs.isNullOrEmpty()) {
            val matchesOfficial = theirs.any { cert ->
                sha256(cert).equals(OFFICIAL_SIGNER_SHA256, ignoreCase = true)
            }
            if (matchesOfficial) return true
        }

        // 2. Check against currently running app's certificates
        val installedInfo = try {
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
                packageManager.getPackageInfo(
                    context.packageName,
                    PackageManager.PackageInfoFlags.of(flags.toLong())
                )
            } else {
                packageManager.getPackageInfo(context.packageName, flags)
            }
        } catch (e: Exception) {
            null
        }

        val ours = installedInfo?.let { signerCertificates(it) }

        if (!ours.isNullOrEmpty() && !theirs.isNullOrEmpty()) {
            val matchesCurrent = ours.any { ourCert ->
                theirs.any { theirCert -> ourCert.contentEquals(theirCert) }
            }
            if (matchesCurrent) return true
        }

        // 3. In debug builds, allow installation so dev/test environments can test updates
        if (BuildConfig.DEBUG) {
            return true
        }

        // 4. A release must not fall through here.
        //
        // `getPackageArchiveInfo` returns null - and so leaves `theirs` empty -
        // for anything it cannot parse as an installed package: a zip that is
        // not an APK, an APK with no signature block, or an unreadable one. The
        // previous version returned `true` in that case for *every* build, on
        // the strength of a comment about OEM limitations extracting signatures
        // from uninstalled APKs. That claim is not a reason to trust a release
        // APK: the one thing this function exists to establish is that the
        // download carries AniSequel's key, and "we could not read a key off
        // it" is the absence of that proof rather than a substitute for it.
        //
        // The cost of being strict is a refused update on the rare device that
        // cannot be read, and the message says so. The cost of being lenient is
        // an app whose update channel accepts an APK whose signature was never
        // checked - the exact outcome the pinned fingerprint above exists to
        // prevent.
        return false
    }

    /**
     * The certificates a package is signed with, or null if there are none.
     *
     * Reads `signingInfo` only. The deprecated `PackageInfo.signatures` fallback
     * sat behind the same `SDK_INT >= P` check as the flags above, and P (28) is
     * below the `minSdk = 31` floor. It is also the wrong field to reach for:
     * `signingInfo` is what knows about rotation, which is the entire reason this
     * function exists.
     */
    private fun signerCertificates(info: PackageInfo): List<ByteArray>? {
        val signers = info.signingInfo?.apkContentsSigners?.map { it.toByteArray() }
        if (!signers.isNullOrEmpty()) return signers

        val history = info.signingInfo?.signingCertificateHistory?.map { it.toByteArray() }
        if (!history.isNullOrEmpty()) return history
        return null
    }

    private fun sha256(bytes: ByteArray): String {
        val digest = java.security.MessageDigest.getInstance("SHA-256")
        return digest.digest(bytes).joinToString("") { "%02x".format(it) }
    }

    /** Releases the last downloaded APK, if any. Called before a fresh download. */
    fun clearDownloadedApk() {
        val directory = File(context.cacheDir, DOWNLOAD_DIR)
        directory.listFiles()?.forEach { it.delete() }
    }

    private companion object {
        const val DOWNLOAD_DIR = "updates"
        const val APK_MIME_TYPE = "application/vnd.android.package-archive"
        const val OFFICIAL_SIGNER_SHA256 = "01924c4a7503820489802deb6993e5e030103a1a1a36482ecb54688fa3311f82"
    }
}