package com.example.data.update

import android.content.Context
import android.content.Intent
import android.content.pm.PackageInfo
import android.content.pm.PackageManager
import android.net.Uri
import android.os.Build
import android.provider.Settings
import androidx.core.content.FileProvider
import com.example.BuildConfig
import com.squareup.moshi.Moshi
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.OkHttpClient
import okhttp3.Request
import java.io.File
import java.io.IOException
import java.util.concurrent.TimeUnit

/**
 * Checks GitHub for a newer release, downloads it, and hands it to the system
 * installer.
 *
 * ## Why this exists as a self-contained piece of app code
 *
 * There is no updater library here, deliberately. The only job is: fetch a
 * small JSON file, compare one integer against `BuildConfig.VERSION_CODE`,
 * stream a ~2.5 MB APK into the cache directory, and fire an intent. A library
 * would add a dependency and a Play Services requirement for that, and the app
 * is deliberately not on the Play Store - which is also why this uses
 * `ACTION_VIEW` on a `FileProvider` URI rather than Play Core's in-app update
 * flow.
 *
 * ## What this cannot do
 *
 * It cannot install silently. Since Android 8 every install is user-confirmed,
 * and since Android 11 the app must hold `REQUEST_INSTALL_PACKAGES` *and* have
 * that permission granted per-app in Settings before the installer will even
 * open. [canInstallPackages] and [unknownSourcesSettingsIntent] exist so the UI
 * can say so and send the user there, rather than firing an intent that fails
 * with a bare `ActivityNotFoundException`.
 */
class UpdateManager(private val context: Context) {

    private val moshi = Moshi.Builder().build()

    // Its own client, deliberately not the shared one: that client carries the
    // AniList auth interceptor, and the update manifest is a public file that
    // must never be requested with a user's AniList bearer token attached.
    private val client: OkHttpClient = OkHttpClient.Builder()
        .connectTimeout(15, TimeUnit.SECONDS)
        .readTimeout(30, TimeUnit.SECONDS)
        .build()

    /**
     * Asks GitHub whether something newer exists.
     *
     * Never throws. A failed check is a normal outcome - the user is offline,
     * or GitHub is down - and it must not be able to take down whatever screen
     * asked, so every failure path is folded into [UpdateCheckResult.Failed]
     * with a message that can be shown verbatim.
     */
    suspend fun checkForUpdate(): UpdateCheckResult = withContext(Dispatchers.IO) {
        val installedVersion = BuildConfig.VERSION_NAME

        val body = try {
            val request = Request.Builder()
                .url(UPDATE_MANIFEST_URL)
                // Force a revalidation. OkHttp's cache is per-client and this
                // client has no cache configured, but being explicit costs
                // nothing and survives someone adding one later.
                .header("Cache-Control", "no-cache")
                .build()

            client.newCall(request).execute().use { response ->
                if (!response.isSuccessful) {
                    return@withContext UpdateCheckResult.Failed(
                        "GitHub answered ${response.code}."
                    )
                }
                response.body?.string()
            }
        } catch (e: IOException) {
            return@withContext UpdateCheckResult.Failed(
                "Could not reach GitHub. Check your connection and try again."
            )
        } ?: return@withContext UpdateCheckResult.Failed("GitHub sent an empty response.")

        val manifest = try {
            moshi.adapter(UpdateManifest::class.java).fromJson(body)
        } catch (e: Exception) {
            // Malformed JSON, or a field of the wrong type. Worth saying so:
            // this file is generated by a workflow, so a parse failure is a
            // real signal that the manifest shape changed.
            return@withContext UpdateCheckResult.Failed(
                "The update manifest could not be read."
            )
        } ?: return@withContext UpdateCheckResult.Failed("The update manifest was empty.")

        if (!manifest.isUsable) {
            return@withContext UpdateCheckResult.Failed(
                "The update manifest is missing a download link."
            )
        }

        if (manifest.isNewerThan(BuildConfig.VERSION_CODE.toLong())) {
            UpdateCheckResult.Available(manifest)
        } else {
            UpdateCheckResult.UpToDate(installedVersion)
        }
    }

    /**
     * Streams the APK into the cache directory.
     *
     * Writes to a `.part` file and renames on completion, so a download
     * interrupted by a phone call or a process death cannot leave a truncated
     * APK behind that a later run would happily hand to the package installer -
     * which fails with an opaque `INSTALL_PARSE_FAILED_NO_CERTIFICATES` or, worse,
     * appears to succeed.
     */
    suspend fun download(
        manifest: UpdateManifest,
        onProgress: (bytesRead: Long, totalBytes: Long) -> Unit = { _, _ -> }
    ): UpdateDownloadResult = withContext(Dispatchers.IO) {
        val url = manifest.downloadUrl.orEmpty()
        if (url.isBlank()) {
            return@withContext UpdateDownloadResult.Failed("That release has no download.")
        }

        try {
            val request = Request.Builder().url(url).build()

            client.newCall(request).execute().use { response ->
                if (!response.isSuccessful) {
                    return@withContext UpdateDownloadResult.Failed(
                        "The download failed (${response.code})."
                    )
                }

                val body = response.body ?: return@withContext UpdateDownloadResult.Failed(
                    "The download came back empty."
                )

                // Bounded: the manifest declares a size and it matched in every
                // release so far. A wildly larger body means the URL is not
                // serving an APK, and writing it to disk would fill the user's
                // storage on a download they never asked for.
                val declaredSize = manifest.sizeBytes ?: 0L
                if (declaredSize > 0 && body.contentLength() > declaredSize * 2) {
                    return@withContext UpdateDownloadResult.Failed(
                        "The download was much larger than expected. Skipped."
                    )
                }

                var partial: File? = null
                try {
                    val directory = File(context.cacheDir, DOWNLOAD_DIR).apply { mkdirs() }
                    val target = File(directory, "anisequel-${manifest.version ?: "update"}.apk")
                    val partFile = File(directory, "${target.name}.part")
                    partial = partFile

                    body.byteStream().use { input ->
                        partFile.outputStream().use { output ->
                            val buffer = ByteArray(DEFAULT_BUFFER_SIZE)
                            val total = body.contentLength().takeIf { it > 0 } ?: declaredSize
                            var read: Long = 0

                            while (true) {
                                val count = input.read(buffer)
                                if (count == -1) break
                                output.write(buffer, 0, count)
                                read += count
                                onProgress(read, total)
                            }

                            output.flush()
                        }
                    }

                    // A 200 response is not proof the body is an APK. A redirect
                    // that lands on an HTML error page, or a rate-limit notice,
                    // is still a successful HTTP response, and the size guard
                    // above only catches bodies that are too *large* - so that
                    // page would be written out as anisequel-<version>.apk and
                    // handed to the package installer, which fails with an
                    // opaque parse error and nothing on screen to explain it.
                    // Every APK is a zip and every zip opens with a local file
                    // header, so four bytes are enough to tell them apart.
                    val looksLikeApk = partFile.inputStream().use { stream ->
                        val magic = ByteArray(4)
                        stream.read(magic) == 4 &&
                            magic[0] == 0x50.toByte() &&
                            magic[1] == 0x4B.toByte() &&
                            magic[2] == 0x03.toByte() &&
                            magic[3] == 0x04.toByte()
                    }

                    if (!looksLikeApk) {
                        partFile.delete()
                        return@withContext UpdateDownloadResult.Failed(
                            "That download was not an APK, so nothing was installed."
                        )
                    }

                    // Being a zip is not the same as being *our* app. Until this
                    // existed, whatever the URL served was handed straight to the
                    // package installer: a release asset replaced at the CDN, a
                    // hijacked mirror, or a future mistake in the manifest's
                    // download_url would all install, and the failure mode is a
                    // successful install of someone else's code.
                    //
                    // Android will not let a different key update an existing
                    // app, so this mostly protects against a first install from
                    // a tampered manifest rather than a silent upgrade - but it
                    // also catches a mismatched build *before* the user reaches a
                    // system dialog that says only "App not installed".
                    if (!isSignedByThisApp(partFile)) {
                        partFile.delete()
                        return@withContext UpdateDownloadResult.Failed(
                            "That APK is not signed with AniSequel's key, so it was not " +
                                "installed. The release may have been tampered with."
                        )
                    }

                    if (!partFile.renameTo(target)) {
                        partFile.delete()
                        return@withContext UpdateDownloadResult.Failed(
                            "Could not save the download."
                        )
                    }

                    UpdateDownloadResult.Success(target, manifest)
                } catch (e: Exception) {
                    partial?.delete()
                    throw e
                }
            }
        } catch (e: Exception) {
            UpdateDownloadResult.Failed(
                e.message?.takeIf { it.isNotBlank() } ?: "The download failed. Check your connection."
            )
        }
    }

    /**
     * The intent that opens the system installer on a downloaded APK.
     *
     * `canInstallPackages` must have been checked first: on Android 8 and
     * later the intent throws `ActivityNotFoundException` when the app has not
     * been granted `REQUEST_INSTALL_PACKAGES`, which reads to the user as the
     * app crashing at the moment they were most expecting progress.
     */
    fun installIntent(apk: File): Intent {
        val uri = FileProvider.getUriForFile(
            context,
            "${context.packageName}.fileprovider",
            apk
        )

        return Intent(Intent.ACTION_VIEW).apply {
            setDataAndType(uri, APK_MIME_TYPE)
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
            addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        }
    }

    /**
     * Whether the system will let this app open the installer right now.
     *
     * Below Android 8, installing is not gated at all, so the answer is always
     * yes. From 8 it is a per-app permission the user has to grant once in
     * Settings, and it is *not* granted by the manifest declaration - declaring
     * it only puts the app in the list of packages that are allowed to ask.
     */
    fun canInstallPackages(): Boolean =
        Build.VERSION.SDK_INT < Build.VERSION_CODES.O || context.packageManager.canRequestPackageInstalls()

    /**
     * The Settings screen where that permission is granted, for the case where
     * [canInstallPackages] is false. Returns null below Android 8, where there
     * is nothing to grant.
     */
    fun unknownSourcesSettingsIntent(): Intent? {
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.O) return null
        return Intent(
            Settings.ACTION_MANAGE_UNKNOWN_APP_SOURCES,
            Uri.parse("package:${context.packageName}")
        )
    }

    /**
     * Whether [apk] is signed by AniSequel's official key or matches the running app's key.
     *
     * Validates against:
     * 1. AniSequel's pinned official release signing certificate SHA-256
     * 2. The currently installed app's signing certificates or rotation history
     *
     * A debug build additionally accepts anything, so a locally signed APK can
     * be exercised end to end. A release build accepts nothing it could not
     * positively identify.
     */
    private fun isSignedByThisApp(apk: File): Boolean {
        val packageManager = context.packageManager

        val flags = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
            PackageManager.GET_SIGNING_CERTIFICATES or PackageManager.GET_SIGNATURES
        } else {
            @Suppress("DEPRECATION")
            PackageManager.GET_SIGNATURES
        }

        val archiveInfo = try {
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
                packageManager.getPackageArchiveInfo(
                    apk.absolutePath,
                    PackageManager.PackageInfoFlags.of(flags.toLong())
                )
            } else {
                packageManager.getPackageArchiveInfo(apk.absolutePath, flags)
            }
        } catch (e: Exception) {
            null
        }

        // Validate package name if readable
        if (archiveInfo?.packageName != null && archiveInfo.packageName != context.packageName) {
            return false
        }

        val theirs = archiveInfo?.let { signerCertificates(it) }

        // 1. Check against AniSequel's pinned official release key
        if (!theirs.isNullOrEmpty()) {
            val matchesOfficial = theirs.any { cert ->
                sha256(cert).equals(OFFICIAL_SIGNER_SHA256, ignoreCase = true)
            }
            if (matchesOfficial) return true
        }

        // 2. Check against currently running app's certificates
        val installedInfo = try {
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
                packageManager.getPackageInfo(
                    context.packageName,
                    PackageManager.PackageInfoFlags.of(flags.toLong())
                )
            } else {
                packageManager.getPackageInfo(context.packageName, flags)
            }
        } catch (e: Exception) {
            null
        }

        val ours = installedInfo?.let { signerCertificates(it) }

        if (!ours.isNullOrEmpty() && !theirs.isNullOrEmpty()) {
            val matchesCurrent = ours.any { ourCert ->
                theirs.any { theirCert -> ourCert.contentEquals(theirCert) }
            }
            if (matchesCurrent) return true
        }

        // 3. In debug builds, allow installation so dev/test environments can test updates
        if (BuildConfig.DEBUG) {
            return true
        }

        // 4. A release must not fall through here.
        //
        // `getPackageArchiveInfo` returns null - and so leaves `theirs` empty -
        // for anything it cannot parse as an installed package: a zip that is
        // not an APK, an APK with no signature block, or an unreadable one. The
        // previous version returned `true` in that case for *every* build, on
        // the strength of a comment about OEM limitations extracting signatures
        // from uninstalled APKs. That claim is not a reason to trust a release
        // APK: the one thing this function exists to establish is that the
        // download carries AniSequel's key, and "we could not read a key off
        // it" is the absence of that proof rather than a substitute for it.
        //
        // The cost of being strict is a refused update on the rare device that
        // cannot be read, and the message says so. The cost of being lenient is
        // an app whose update channel accepts an APK whose signature was never
        // checked - the exact outcome the pinned fingerprint above exists to
        // prevent.
        return false
    }

    /** The certificates a package is signed with, or null if there are none. */
    private fun signerCertificates(info: PackageInfo): List<ByteArray>? {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
            val signers = info.signingInfo?.apkContentsSigners?.map { it.toByteArray() }
            if (!signers.isNullOrEmpty()) return signers

            val history = info.signingInfo?.signingCertificateHistory?.map { it.toByteArray() }
            if (!history.isNullOrEmpty()) return history
        }
        @Suppress("DEPRECATION")
        val legacy = info.signatures?.map { it.toByteArray() }
        if (!legacy.isNullOrEmpty()) return legacy
        return null
    }

    private fun sha256(bytes: ByteArray): String {
        val digest = java.security.MessageDigest.getInstance("SHA-256")
        return digest.digest(bytes).joinToString("") { "%02x".format(it) }
    }

    /** Releases the last downloaded APK, if any. Called before a fresh download. */
    fun clearDownloadedApk() {
        val directory = File(context.cacheDir, DOWNLOAD_DIR)
        directory.listFiles()?.forEach { it.delete() }
    }

    private companion object {
        const val DOWNLOAD_DIR = "updates"
        const val APK_MIME_TYPE = "application/vnd.android.package-archive"
        const val OFFICIAL_SIGNER_SHA256 = "c33eceb9ccf48378c8ec8fc7c1d72b0340638d2d824a4aa3db96c8e8f1c0e4ab"
    }
}