package com.example.data.update

import android.content.Context
import android.content.Intent
import android.net.Uri
import android.os.Build
import android.provider.Settings
import androidx.core.content.FileProvider
import com.example.BuildConfig
import com.squareup.moshi.Moshi
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.OkHttpClient
import okhttp3.Request
import java.io.File
import java.io.IOException
import java.util.concurrent.TimeUnit

/**
 * Checks GitHub for a newer release, downloads it, and hands it to the system
 * installer.
 *
 * ## Why this exists as a self-contained piece of app code
 *
 * There is no updater library here, deliberately. The only job is: fetch a
 * small JSON file, compare one integer against `BuildConfig.VERSION_CODE`,
 * stream a ~2.5 MB APK into the cache directory, and fire an intent. A library
 * would add a dependency and a Play Services requirement for that, and the app
 * is deliberately not on the Play Store - which is also why this uses
 * `ACTION_VIEW` on a `FileProvider` URI rather than Play Core's in-app update
 * flow.
 *
 * ## What this cannot do
 *
 * It cannot install silently. Since Android 8 every install is user-confirmed,
 * and since Android 11 the app must hold `REQUEST_INSTALL_PACKAGES` *and* have
 * that permission granted per-app in Settings before the installer will even
 * open. [canInstallPackages] and [unknownSourcesSettingsIntent] exist so the UI
 * can say so and send the user there, rather than firing an intent that fails
 * with a bare `ActivityNotFoundException`.
 */
class UpdateManager(private val context: Context) {

    private val moshi = Moshi.Builder().build()

    // Its own client, deliberately not the shared one: that client carries the
    // AniList auth interceptor, and the update manifest is a public file that
    // must never be requested with a user's AniList bearer token attached.
    private val client: OkHttpClient = OkHttpClient.Builder()
        .connectTimeout(15, TimeUnit.SECONDS)
        .readTimeout(30, TimeUnit.SECONDS)
        .build()

    /**
     * Asks GitHub whether something newer exists.
     *
     * Never throws. A failed check is a normal outcome - the user is offline,
     * or GitHub is down - and it must not be able to take down whatever screen
     * asked, so every failure path is folded into [UpdateCheckResult.Failed]
     * with a message that can be shown verbatim.
     */
    suspend fun checkForUpdate(): UpdateCheckResult = withContext(Dispatchers.IO) {
        val installedVersion = BuildConfig.VERSION_NAME

        val body = try {
            val request = Request.Builder()
                .url(UPDATE_MANIFEST_URL)
                // Force a revalidation. OkHttp's cache is per-client and this
                // client has no cache configured, but being explicit costs
                // nothing and survives someone adding one later.
                .header("Cache-Control", "no-cache")
                .build()

            client.newCall(request).execute().use { response ->
                if (!response.isSuccessful) {
                    return@withContext UpdateCheckResult.Failed(
                        "GitHub answered ${response.code}."
                    )
                }
                response.body?.string()
            }
        } catch (e: IOException) {
            return@withContext UpdateCheckResult.Failed(
                "Could not reach GitHub. Check your connection and try again."
            )
        } ?: return@withContext UpdateCheckResult.Failed("GitHub sent an empty response.")

        val manifest = try {
            moshi.adapter(UpdateManifest::class.java).fromJson(body)
        } catch (e: Exception) {
            // Malformed JSON, or a field of the wrong type. Worth saying so:
            // this file is generated by a workflow, so a parse failure is a
            // real signal that the manifest shape changed.
            return@withContext UpdateCheckResult.Failed(
                "The update manifest could not be read."
            )
        } ?: return@withContext UpdateCheckResult.Failed("The update manifest was empty.")

        if (!manifest.isUsable) {
            return@withContext UpdateCheckResult.Failed(
                "The update manifest is missing a download link."
            )
        }

        if (manifest.isNewerThan(BuildConfig.VERSION_CODE.toLong())) {
            UpdateCheckResult.Available(manifest)
        } else {
            UpdateCheckResult.UpToDate(installedVersion)
        }
    }

    /**
     * Streams the APK into the cache directory.
     *
     * Writes to a `.part` file and renames on completion, so a download
     * interrupted by a phone call or a process death cannot leave a truncated
     * APK behind that a later run would happily hand to the package installer -
     * which fails with an opaque `INSTALL_PARSE_FAILED_NO_CERTIFICATES` or, worse,
     * appears to succeed.
     */
    suspend fun download(
        manifest: UpdateManifest,
        onProgress: (bytesRead: Long, totalBytes: Long) -> Unit = { _, _ -> }
    ): UpdateDownloadResult = withContext(Dispatchers.IO) {
        val url = manifest.downloadUrl.orEmpty()
        if (url.isBlank()) {
            return@withContext UpdateDownloadResult.Failed("That release has no download.")
        }

        try {
            val request = Request.Builder().url(url).build()

            client.newCall(request).execute().use { response ->
                if (!response.isSuccessful) {
                    return@withContext UpdateDownloadResult.Failed(
                        "The download failed (${response.code})."
                    )
                }

                val body = response.body ?: return@withContext UpdateDownloadResult.Failed(
                    "The download came back empty."
                )

                // Bounded: the manifest declares a size and it matched in every
                // release so far. A wildly larger body means the URL is not
                // serving an APK, and writing it to disk would fill the user's
                // storage on a download they never asked for.
                val declaredSize = manifest.sizeBytes ?: 0L
                if (declaredSize > 0 && body.contentLength() > declaredSize * 2) {
                    return@withContext UpdateDownloadResult.Failed(
                        "The download was much larger than expected. Skipped."
                    )
                }

                val directory = File(context.cacheDir, DOWNLOAD_DIR).apply { mkdirs() }
                val target = File(directory, "anisequel-${manifest.version ?: "update"}.apk")
                val partial = File(directory, "${target.name}.part")

                // Start from zero every time rather than resuming. A partial
                // resume needs a Range request and a matching ETag; getting
                // that wrong silently produces a corrupt APK, which is a much
                // worse outcome than re-downloading 2.5 MB.
                body.byteStream().use { input ->
                    partial.outputStream().use { output ->
                        val buffer = ByteArray(DEFAULT_BUFFER_SIZE)
                        val total = body.contentLength().takeIf { it > 0 } ?: declaredSize
                        var read: Long = 0

                        while (true) {
                            val count = input.read(buffer)
                            if (count == -1) break
                            output.write(buffer, 0, count)
                            read += count
                            onProgress(read, total)
                        }

                        output.flush()
                    }
                }

                if (!partial.renameTo(target)) {
                    partial.delete()
                    return@withContext UpdateDownloadResult.Failed(
                        "Could not save the download."
                    )
                }

                UpdateDownloadResult.Success(target, manifest)
            }
        } catch (e: IOException) {
            UpdateDownloadResult.Failed("The download failed. Check your connection.")
        }
    }

    /**
     * The intent that opens the system installer on a downloaded APK.
     *
     * `canInstallPackages` must have been checked first: on Android 8 and
     * later the intent throws `ActivityNotFoundException` when the app has not
     * been granted `REQUEST_INSTALL_PACKAGES`, which reads to the user as the
     * app crashing at the moment they were most expecting progress.
     */
    fun installIntent(apk: File): Intent {
        val uri = FileProvider.getUriForFile(
            context,
            "${context.packageName}.fileprovider",
            apk
        )

        return Intent(Intent.ACTION_VIEW).apply {
            setDataAndType(uri, APK_MIME_TYPE)
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
            addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        }
    }

    /**
     * Whether the system will let this app open the installer right now.
     *
     * Below Android 8, installing is not gated at all, so the answer is always
     * yes. From 8 it is a per-app permission the user has to grant once in
     * Settings, and it is *not* granted by the manifest declaration - declaring
     * it only puts the app in the list of packages that are allowed to ask.
     */
    fun canInstallPackages(): Boolean =
        Build.VERSION.SDK_INT < Build.VERSION_CODES.O || context.packageManager.canRequestPackageInstalls()

    /**
     * The Settings screen where that permission is granted, for the case where
     * [canInstallPackages] is false. Returns null below Android 8, where there
     * is nothing to grant.
     */
    fun unknownSourcesSettingsIntent(): Intent? {
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.O) return null
        return Intent(
            Settings.ACTION_MANAGE_UNKNOWN_APP_SOURCES,
            Uri.parse("package:${context.packageName}")
        )
    }

    /** Releases the last downloaded APK, if any. Called before a fresh download. */
    fun clearDownloadedApk() {
        val directory = File(context.cacheDir, DOWNLOAD_DIR)
        directory.listFiles()?.forEach { it.delete() }
    }

    private companion object {
        const val DOWNLOAD_DIR = "updates"
        const val APK_MIME_TYPE = "application/vnd.android.package-archive"
    }
}